defaults:
  - colors

colors:
  cmap: 22
  team:
    no_team: null
    prediction:
      left: [ 0, 0, 255 ]
      right: [ 255, 0, 0 ]
      referee: [ 238, 210, 2 ]
    ground_truth:
      left: [ 0, 255, 0 ]
      right: [ 0, 255, 0 ]
      referee: [ 255, 255, 0 ]
